/*
    Lesson 25 — TypeScript Utility Types

    In this lesson I am learning built-in utility types.

    Instead of creating slightly different versions
    of the same type manually, TypeScript gives me
    utility types that can transform existing types.
*/


/*
    1. Partial<T>

    Partial makes every property optional.

    This is useful for update objects because
    I may only want to update one or two properties.
*/

type User = {
    id: number;
    name: string;
    email: string;
    password: string;
};

type UpdateUser = Partial<User>;

const updateUser: UpdateUser = {
    name: "Vivek"
};


/*
    2. Required<T>

    Required does the opposite of Partial.

    If properties are optional in the original type,
    Required makes them required.
*/

type OptionalUser = {
    name?: string;
    age?: number;
};

type CompleteUser = Required<OptionalUser>;

const completeUser: CompleteUser = {
    name: "Vivek",
    age: 20
};


/*
    3. Readonly<T>

    Readonly prevents me from reassigning
    properties through this type.

    It is useful when I want to treat an object
    as read-only.
*/

type UserProfile = {
    name: string;
    age: number;
};

const profile: Readonly<UserProfile> = {
    name: "Vivek",
    age: 20
};

// profile.age = 21;


/*
    4. Pick<T, K>

    Pick allows me to keep only the properties
    I select from an existing type.

    Here I only need id and name.
*/

type UserPreview = Pick<User, "id" | "name">;

const preview: UserPreview = {
    id: 1,
    name: "Vivek"
};


/*
    5. Omit<T, K>

    Omit does the opposite of Pick.

    It removes the properties I specify.

    Here I don't want the password in the
    public user object.
*/

type PublicUser = Omit<User, "password">;

const publicUser: PublicUser = {
    id: 1,
    name: "Vivek",
    email: "vivek@gmail.com"
};


/*
    6. Record<K, T>

    Record creates an object type using:

    K = keys
    T = value type

    Here every role must exist and
    every value must be a boolean.
*/

type Role = "admin" | "user" | "guest";

type RolePermissions = Record<Role, boolean>;

const permissions: RolePermissions = {
    admin: true,
    user: true,
    guest: false
};


/*
    Utility types become more useful when
    I combine them.

    For example, when creating a user,
    I don't need the id because it can be
    generated by the database.
*/

type CreateUser = Omit<User, "id">;


/*
    For updating a user:

    1. Omit removes id
    2. Partial makes the remaining properties optional

    This means I can update only the fields I need.
*/

type UserUpdate = Partial<Omit<User, "id">>;

const userUpdate: UserUpdate = {
    email: "newemail@gmail.com"
};


/*
    For an API response, I may not want
    to send sensitive information such as
    the password to the client.
*/

type UserResponse = Omit<User, "password">;

const userResponse: UserResponse = {
    id: 1,
    name: "Vivek",
    email: "vivek@gmail.com"
};


/*
    Final mental model:

    Partial  -> make properties optional
    Required -> make properties required
    Readonly -> prevent property reassignment
    Pick     -> keep selected properties
    Omit     -> remove selected properties
    Record   -> specific keys + value type
*/